### ISSUE TITLE
Redis fetch value issue

### ISSUE THREAD

**Issue by fusion44** [fusion44/blitz_api#156]
```
Oct 14 08:04:03 debian python[3531]: ERROR:uvicorn.error:Exception in ASGI application
Oct 14 08:04:03 debian python[3531]: Traceback (most recent call last):
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
Oct 14 08:04:03 debian python[3531]:     result = await app(  # type: ignore[func-returns-value]
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
Oct 14 08:04:03 debian python[3531]:     return await self.app(scope, receive, send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 269, in __call__
Oct 14 08:04:03 debian python[3531]:     await super().__call__(scope, receive, send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 124, in __call__
Oct 14 08:04:03 debian python[3531]:     await self.middleware_stack(scope, receive, send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 184, in __call__
Oct 14 08:04:03 debian python[3531]:     raise exc
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 162, in __call__
Oct 14 08:04:03 debian python[3531]:     await self.app(scope, receive, _send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/cors.py", line 84, in __call__
Oct 14 08:04:03 debian python[3531]:     await self.app(scope, receive, send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 93, in __call__
Oct 14 08:04:03 debian python[3531]:     raise exc
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 82, in __call__
Oct 14 08:04:03 debian python[3531]:     await self.app(scope, receive, sender)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
Oct 14 08:04:03 debian python[3531]:     raise e
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
Oct 14 08:04:03 debian python[3531]:     await self.app(scope, receive, send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 670, in __call__
Oct 14 08:04:03 debian python[3531]:     await route.handle(scope, receive, send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 418, in handle
Oct 14 08:04:03 debian python[3531]:     await self.app(scope, receive, send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 269, in __call__
Oct 14 08:04:03 debian python[3531]:     await super().__call__(scope, receive, send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 124, in __call__
Oct 14 08:04:03 debian python[3531]:     await self.middleware_stack(scope, receive, send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 184, in __call__
Oct 14 08:04:03 debian python[3531]:     raise exc
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 162, in __call__
Oct 14 08:04:03 debian python[3531]:     await self.app(scope, receive, _send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 93, in __call__
Oct 14 08:04:03 debian python[3531]:     raise exc
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 82, in __call__
Oct 14 08:04:03 debian python[3531]:     await self.app(scope, receive, sender)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
Oct 14 08:04:03 debian python[3531]:     raise e
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
Oct 14 08:04:03 debian python[3531]:     await self.app(scope, receive, send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 670, in __call__
Oct 14 08:04:03 debian python[3531]:     await route.handle(scope, receive, send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 266, in handle
Oct 14 08:04:03 debian python[3531]:     await self.app(scope, receive, send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 65, in app
Oct 14 08:04:03 debian python[3531]:     response = await func(request)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 231, in app
Oct 14 08:04:03 debian python[3531]:     raw_response = await run_endpoint_function(
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 160, in run_endpoint_function
Oct 14 08:04:03 debian python[3531]:     return await dependant.call(**values)
Oct 14 08:04:03 debian python[3531]:   File "./app/routers/setup.py", line 31, in get_status
Oct 14 08:04:03 debian python[3531]:     setupPhase = await redis_get("setupPhase")
Oct 14 08:04:03 debian python[3531]:   File "./app/utils.py", line 64, in redis_get
Oct 14 08:04:03 debian python[3531]:     return v.decode("utf-8")
Oct 14 08:04:03 debian python[3531]: AttributeError: 'str' object has no attribute 'decode'
```

_Originally posted by @benjamin-wilson in https://github.com/rootzoll/raspiblitz/issues/3262#issuecomment-1278925370_

**Comment by ChuckNorrison** [comment]
In some circumstances redis db does return a string object which can not be decoded. This try except will catch it
https://github.com/fusion44/blitz_api/pull/159

**Comment by fusion44** [comment]
Fixed with #159 - Thanks @ChuckNorrison!
