### ISSUE TITLE
Exception when shutting down application: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by cstenglein** [fusion44/blitz_api#26]
When shutting down the application with CTRL+C i get the following error stacktrace:

```
^CINFO:     Shutting down
INFO:     Finished server process [5244]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/christophs/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/christophs/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/christophs/.local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/christophs/.local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/christophs/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/christophs/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/christophs/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/home/christophs/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/christophs/.local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/christophs/.local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/christophs/.local/lib/python3.9/site-packages/starlette/routing.py", line 55, in app
    await response(scope, receive, send)
  File "/home/christophs/src/cloned/blitz_api/./app/sse_starlette.py", line 180, in __call__
    await run_until_first_complete(
  File "/home/christophs/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 22, in run_until_first_complete
    (done, pending) = await asyncio.wait(tasks, return_when=asyncio.FIRST_COMPLETED)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 413, in wait
    return await _wait(fs, timeout, return_when, loop)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 529, in _wait
    await waiter
asyncio.exceptions.CancelledError
INFO:     ASGI 'lifespan' protocol appears unsupported.
Exception in callback _SelectorSocketTransport._call_connection_lost(None)
handle: <Handle _SelectorSocketTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 978, in _call_connection_lost
    super()._call_connection_lost(exc)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 736, in _call_connection_lost
    self._protocol.connection_lost(exc)
  File "/home/christophs/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 117, in connection_lost
    self.on_connection_lost()
  File "/home/christophs/.local/lib/python3.9/site-packages/uvicorn/_handlers/http.py", line 42, in <lambda>
    on_connection_lost=lambda: connection_lost.set_result(True),
asyncio.exceptions.InvalidStateError: invalid state
Exception in callback handle_http.<locals>.retrieve_exception(<Task cancell...erver.py:104>>) at /home/christophs/.local/lib/python3.9/site-packages/uvicorn/_handlers/http.py:56
handle: <Handle handle_http.<locals>.retrieve_exception(<Task cancell...erver.py:104>>) at /home/christophs/.local/lib/python3.9/site-packages/uvicorn/_handlers/http.py:56>
Traceback (most recent call last):
  File "/home/christophs/.local/lib/python3.9/site-packages/uvicorn/server.py", line 107, in handler
    await handle_http(
  File "/home/christophs/.local/lib/python3.9/site-packages/uvicorn/_handlers/http.py", line 87, in handle_http
    await connection_lost
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/christophs/.local/lib/python3.9/site-packages/uvicorn/_handlers/http.py", line 58, in retrieve_exception
    exc = task.exception()
asyncio.exceptions.CancelledError
unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-104' coro=<EventSourceResponse.stream_response() done, defined at /home/christophs/src/cloned/blitz_api/./app/sse_starlette.py:192> exception=TypeError("'NoneType' object is not callable")>
Traceback (most recent call last):
  File "/home/christophs/src/cloned/blitz_api/./app/sse_starlette.py", line 210, in stream_response
    await send({"type": "http.response.body", "body": b"", "more_body": False})
  File "/home/christophs/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 68, in sender
    await send(message)
  File "/home/christophs/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 148, in send
    await send(message)
  File "/home/christophs/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 156, in _send
    await send(message)
  File "/home/christophs/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 490, in send
    self.on_response()
TypeError: 'NoneType' object is not callable
INFO:     Stopping reloader process [5242]
```

**Comment by fusion44** [comment]
Does this still happen for you?

**Comment by cstenglein** [comment]
Yes, but only sometimes when shutting a local install, so can be closed for now.
